import "./globals.css";
import NavBar from './components/NavBar'
export const metadata = {
  title: "My-portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-sky-100 text-stone-900 dark:bg-primary dark:text-cyan-50">
      <NavBar />
        {children}
      </body>
    </html>
  );
}
